import os, random, math, hashlib, time, json, threading
from datetime import datetime, timezone

HOST = os.getenv("HOST", "0.0.0.0")
PORT = int(os.getenv("PORT", "5001"))
CORS_ORIGINS = ["http://localhost:3000", "http://127.0.0.1:3000", "*"]

# ============================================================
# CHAINS — 100+ chains across ALL VM families
# ============================================================
CHAINS = [
    # --- EVM L1s ---
    {"id": "ethereum", "name": "Ethereum Mainnet", "vm": "EVM", "chainId": 1, "status": "active", "rpc": "https://eth.llamarpc.com", "explorer": "https://etherscan.io", "currency": "ETH"},
    {"id": "bsc", "name": "BNB Smart Chain", "vm": "EVM", "chainId": 56, "status": "active", "rpc": "https://bsc-rpc.publicnode.com", "explorer": "https://bscscan.com", "currency": "BNB"},
    {"id": "avalanche", "name": "Avalanche C-Chain", "vm": "EVM", "chainId": 43114, "status": "active", "rpc": "https://api.avax.network/ext/bc/C/rpc", "explorer": "https://snowtrace.io", "currency": "AVAX"},
    {"id": "fantom", "name": "Fantom Opera", "vm": "EVM", "chainId": 250, "status": "active", "rpc": "https://fantom.publicnode.com", "explorer": "https://ftmscan.com", "currency": "FTM"},
    {"id": "cronos", "name": "Cronos", "vm": "EVM", "chainId": 25, "status": "active", "rpc": "https://evm.cronos.org", "explorer": "https://cronoscan.com", "currency": "CRO"},
    {"id": "celo", "name": "Celo", "vm": "EVM", "chainId": 42220, "status": "active", "rpc": "https://forno.celo.org", "explorer": "https://celoscan.io", "currency": "CELO"},
    {"id": "flare", "name": "Flare", "vm": "EVM", "chainId": 14, "status": "indexing", "rpc": "https://rpc.ankr.com/flare", "explorer": "https://flarescan.com", "currency": "FLR"},
    {"id": "kava", "name": "Kava EVM", "vm": "EVM", "chainId": 2222, "status": "active", "rpc": "https://evm.kava.io", "explorer": "https://kavascan.com", "currency": "KAVA"},
    {"id": "evmos", "name": "Evmos", "vm": "EVM", "chainId": 9001, "status": "active", "rpc": "https://evmos-rpc.publicnode.com", "explorer": "https://evmos.bigdipper.live", "currency": "EVMOS"},
    {"id": "theta", "name": "Theta Mainnet", "vm": "EVM", "chainId": 361, "status": "active", "rpc": "https://eth-rpc-api.thetatoken.org", "explorer": "https://explorer.thetatoken.org", "currency": "THETA"},
    # --- EVM L2s ---
    {"id": "arbitrum", "name": "Arbitrum One", "vm": "EVM", "chainId": 42161, "status": "active", "rpc": "https://arb1.arbitrum.io/rpc", "explorer": "https://arbiscan.io", "currency": "ETH"},
    {"id": "optimism", "name": "Optimism", "vm": "EVM", "chainId": 10, "status": "active", "rpc": "https://mainnet.optimism.io", "explorer": "https://optimistic.etherscan.io", "currency": "ETH"},
    {"id": "base", "name": "Base", "vm": "EVM", "chainId": 8453, "status": "active", "rpc": "https://mainnet.base.org", "explorer": "https://basescan.org", "currency": "ETH"},
    {"id": "polygon", "name": "Polygon PoS", "vm": "EVM", "chainId": 137, "status": "active", "rpc": "https://polygon-rpc.com", "explorer": "https://polygonscan.com", "currency": "MATIC"},
    {"id": "zksync", "name": "zkSync Era", "vm": "zkEVM", "chainId": 324, "status": "active", "rpc": "https://mainnet.era.zksync.io", "explorer": "https://explorer.zksync.io", "currency": "ETH"},
    {"id": "mantle", "name": "Mantle", "vm": "EVM", "chainId": 5000, "status": "indexing", "rpc": "https://rpc.mantle.xyz", "explorer": "https://mantlescan.xyz", "currency": "MNT"},
    {"id": "linea", "name": "Linea", "vm": "zkEVM", "chainId": 59144, "status": "active", "rpc": "https://rpc.linea.build", "explorer": "https://lineascan.build", "currency": "ETH"},
    {"id": "scroll", "name": "Scroll", "vm": "zkEVM", "chainId": 534352, "status": "active", "rpc": "https://rpc.scroll.io", "explorer": "https://scrollscan.com", "currency": "ETH"},
    {"id": "mode", "name": "Mode", "vm": "EVM", "chainId": 34443, "status": "active", "rpc": "https://mainnet.mode.network", "explorer": "https://explorer.mode.network", "currency": "ETH"},
    {"id": "zora", "name": "Zora", "vm": "EVM", "chainId": 7777777, "status": "active", "rpc": "https://rpc.zora.energy", "explorer": "https://explorer.zora.energy", "currency": "ETH"},
    {"id": "bob", "name": "BOB", "vm": "EVM", "chainId": 60808, "status": "indexing", "rpc": "https://mainnet.bob-build.com", "explorer": "https://explorer.bob-build.com", "currency": "ETH"},
    {"id": "fraxtal", "name": "Fraxtal", "vm": "EVM", "chainId": 252, "status": "active", "rpc": "https://rpc.fraxtal.com", "explorer": "https://fraxscan.com", "currency": "FRAX"},
    {"id": "metis", "name": "Metis Andromeda", "vm": "EVM", "chainId": 1088, "status": "active", "rpc": "https://andromeda.metis.io", "explorer": "https://andromeda-explorer.metis.io", "currency": "METIS"},
    {"id": "soneium", "name": "Soneium Minato", "vm": "EVM", "chainId": 1946, "status": "indexing", "rpc": "https://rpc.minato.soneium.org", "explorer": "https://soneium.blockscout.com", "currency": "ETH"},
    {"id": "boba", "name": "Boba Network", "vm": "EVM", "chainId": 288, "status": "active", "rpc": "https://mainnet.boba.network", "explorer": "https://bobascan.com", "currency": "BOBA"},
    {"id": "loom", "name": "Loom Network", "vm": "EVM", "chainId": 10143, "status": "active", "rpc": "https://rpc.loom.network", "explorer": "https://blockscout.loomx.io", "currency": "LOOM"},
    {"id": "kroma", "name": "Kroma", "vm": "zkEVM", "chainId": 255, "status": "active", "rpc": "https://rpc.kroma.network", "explorer": "https://kromascan.com", "currency": "ETH"},
    {"id": "mars", "name": "Mars Protocol", "vm": "EVM", "chainId": 44787, "status": "observation", "rpc": "https://rpc.marsprotocol.io", "explorer": "https://explorer.marsprotocol.io", "currency": "MARS"},
    # --- EVM Appchains ---
    {"id": "aurelia", "name": "Aurora", "vm": "EVM", "chainId": 1313161555, "status": "active", "rpc": "https://mainnet.aurora.dev", "explorer": "https://explorer.aurora.dev", "currency": "AURORA"},
    {"id": "astar", "name": "Astar EVM", "vm": "EVM", "chainId": 592, "status": "active", "rpc": "https://evm.astar.network", "explorer": "https://blockscout.astar.network", "currency": "ASTR"},
    {"id": "shiden", "name": "Shiden EVM", "vm": "EVM", "chainId": 336, "status": "active", "rpc": "https://evm.shiden.astar.network", "explorer": "https://shiden.blockscout.com", "currency": "SDN"},
    {"id": "gnosis", "name": "Gnosis Chain", "vm": "EVM", "chainId": 100, "status": "active", "rpc": "https://rpc.gnosischain.com", "explorer": "https://gnosisscan.io", "currency": "xDAI"},
    {"id": "hsk", "name": "HashKey Chain", "vm": "EVM", "chainId": 177, "status": "active", "rpc": "https://mainnet.hsk.xyz", "explorer": "https://explorer.hsk.xyz", "currency": "HSK"},
    {"id": "botchain", "name": "BOT Chain", "vm": "EVM", "chainId": 677, "status": "active", "rpc": "https://rpc.botchain.ai", "explorer": "https://scan.botchain.ai/", "currency": "BOT"},
    {"id": "moonriver", "name": "Moonriver", "vm": "EVM", "chainId": 1285, "status": "active", "rpc": "https://rpc.moonriver.moonbeam.network", "explorer": "https://moonriver.moonscan.io", "currency": "MOVR"},
    {"id": "moonbeam", "name": "Moonbeam", "vm": "EVM", "chainId": 1284, "status": "active", "rpc": "https://rpc.api.moonbeam.network", "explorer": "https://moonbeam.moonscan.io", "currency": "GLMR"},
    {"id": "blast", "name": "Blast", "vm": "EVM", "chainId": 81457, "status": "active", "rpc": "https://rpc.blast.io", "explorer": "https://blastscan.io", "currency": "ETH"},
    {"id": "pgn", "name": "Public Goods Network", "vm": "EVM", "chainId": 424, "status": "active", "rpc": "https://rpc.publicgoods.network", "explorer": "https://explorer.publicgoods.network", "currency": "ETH"},
    {"id": "ancient8", "name": "Ancient8", "vm": "EVM", "chainId": 888888888, "status": "active", "rpc": "https://rpc.ancient8.gg", "explorer": "https://scan.ancient8.gg", "currency": "A8"},
    {"id": "sei", "name": "Sei EVM", "vm": "EVM", "chainId": 1329, "status": "active", "rpc": "https://evm-rpc.sei.io", "explorer": "https://seitrace.com", "currency": "SEI"},
    {"id": "nakamoto", "name": "Stacks Nakamoto", "vm": "EVM", "chainId": 1, "status": "indexing", "rpc": "https://api.mainnet.hiro.so", "explorer": "https://explorer.stacks.co", "currency": "STX"},
    # --- SVM (Solana VM) ---
    {"id": "solana", "name": "Solana", "vm": "SVM", "chainId": 103, "status": "active", "rpc": "https://api.mainnet-beta.solana.com", "explorer": "https://explorer.solana.com", "currency": "SOL"},
    {"id": "sonic", "name": "Sonic", "vm": "SVM", "chainId": 146, "status": "active", "rpc": "https://mainnet.sonic.gg", "explorer": "https://explorer.sonic.gg", "currency": "SONIC"},
    {"id": "eclipse", "name": "Eclipse", "vm": "SVM", "chainId": 1314, "status": "active", "rpc": "https://mainnet.eclipse.build", "explorer": "https://explorer.eclipse.build", "currency": "ETH"},
    {"id": "tensorflow", "name": "TensorFi", "vm": "SVM", "chainId": 8764, "status": "observation", "rpc": "https://rpc.tensorfi.io", "explorer": "https://explorer.tensorfi.io", "currency": "TENSOR"},
    {"id": "nexus", "name": "Nexus SVM", "vm": "SVM", "chainId": 889, "status": "indexing", "rpc": "https://rpc.nexus.xyz", "explorer": "https://explorer.nexus.xyz", "currency": "NXS"},
    # --- WASM ---
    {"id": "near", "name": "NEAR Protocol", "vm": "WASM", "chainId": 1313161554, "status": "active", "rpc": "https://rpc.mainnet.near.org", "explorer": "https://nearblocks.io", "currency": "NEAR"},
    {"id": "aurora-ne", "name": "Aurora (NEAR native)", "vm": "WASM", "chainId": 1313161555, "status": "active", "rpc": "https://rpc.mainnet.aurora.dev", "explorer": "https://aurora.dev", "currency": "AURORA"},
    {"id": "oasis", "name": "Oasis Sapphire", "vm": "WASM", "chainId": 23294, "status": "active", "rpc": "https://sapphire.oasis.io", "explorer": "https://explorer.oasis.io", "currency": "ROSE"},
    {"id": "peaq", "name": "peaq Network", "vm": "WASM", "chainId": 9999, "status": "active", "rpc": "https://rpc.peaq.network", "explorer": "https://explorer.peaq.network", "currency": "PEAQ"},
    {"id": "kilt", "name": "KILT Protocol", "vm": "WASM", "chainId": 109, "status": "active", "rpc": "https://rpc.peregrine.kilt.io", "explorer": "https://explorer.kilt.io", "currency": "KILT"},
    {"id": "manta", "name": "Manta Pacific", "vm": "WASM", "chainId": 169, "status": "indexing", "rpc": "https://pacific-rpc.manta.network", "explorer": "https://pacific-explorer.manta.network", "currency": "MANTA"},
    # --- Cairo ---
    {"id": "starknet", "name": "StarkNet", "vm": "Cairo", "chainId": 1, "status": "active", "rpc": "https://rpc.starknet.io", "explorer": "https://starkscan.co", "currency": "ETH"},
    {"id": "starknet-fr", "name": "StarkNet Foudroyante", "vm": "Cairo", "chainId": 2, "status": "indexing", "rpc": "https://rpc.foudroyante.starknet.io", "explorer": "https://foudroyante.starkscan.co", "currency": "STRK"},
    {"id": "kakarot", "name": "Kakarot (StarkNet)", "vm": "Cairo", "chainId": 3, "status": "active", "rpc": "https://rpc.kakarot.org", "explorer": "https://explorer.kakarot.org", "currency": "ETH"},
    {"id": "ekubo", "name": "Ekubo (StarkNet)", "vm": "Cairo", "chainId": 4, "status": "active", "rpc": "https://rpc.ekubo.org", "explorer": "https://ekubo.xyz", "currency": "ETH"},
    # --- Move ---
    {"id": "sui", "name": "Sui", "vm": "Move", "chainId": 1, "status": "active", "rpc": "https://fullnode.mainnet.sui.io", "explorer": "https://suiscan.xyz", "currency": "SUI"},
    {"id": "aptos", "name": "Aptos", "vm": "Move", "chainId": 1, "status": "indexing", "rpc": "https://fullnode.mainnet.aptoslabs.com", "explorer": "https://aptoscan.com", "currency": "APT"},
    {"id": "movement", "name": "Movement", "vm": "Move", "chainId": 2, "status": "active", "rpc": "https://rpc.movementnetwork.xyz", "explorer": "https://explorer.movementnetwork.xyz", "currency": "MOVE"},
    {"id": "0L", "name": "0L Network", "vm": "Move", "chainId": 3, "status": "observation", "rpc": "https://rpc.0l.network", "explorer": "https://explorer.0l.network", "currency": "GAS"},
    # --- TVM ---
    {"id": "ton", "name": "TON", "vm": "TVM", "chainId": -239, "status": "active", "rpc": "https://toncenter.com/api/v2", "explorer": "https://tonviewer.com", "currency": "TON"},
    {"id": "ton-testnet", "name": "TON Testnet", "vm": "TVM", "chainId": -3, "status": "observation", "rpc": "https://testnet.toncenter.com/api/v2", "explorer": "https://testnet.tonscan.org", "currency": "TON"},
    {"id": "notcoin", "name": "Notcoin Chain", "vm": "TVM", "chainId": -240, "status": "indexing", "rpc": "https://rpc.notcoin.org", "explorer": "https://explorer.notcoin.org", "currency": "NOT"},
    # --- CosmWasm ---
    {"id": "cosmos", "name": "Cosmos Hub", "vm": "CosmWasm", "chainId": "cosmoshub-4", "status": "active", "rpc": "https://cosmos-rpc.polkachu.com", "explorer": "https://mintscan.io/cosmos", "currency": "ATOM"},
    {"id": "osmosis", "name": "Osmosis", "vm": "CosmWasm", "chainId": "osmosis-1", "status": "active", "rpc": "https://rpc.osmosis.zone", "explorer": "https://mintscan.io/osmosis", "currency": "OSMO"},
    {"id": "injective", "name": "Injective", "vm": "CosmWasm", "chainId": "injective-1", "status": "active", "rpc": "https://injective-rpc.publicnode.com", "explorer": "https://mintscan.io/injective", "currency": "INJ"},
    {"id": "secret", "name": "Secret Network", "vm": "CosmWasm", "chainId": "secret-4", "status": "active", "rpc": "https://rpc.secret.network", "explorer": "https://mintscan.io/secret", "currency": "SCRT"},
    {"id": "neutron", "name": "Neutron", "vm": "CosmWasm", "chainId": "neutron-1", "status": "active", "rpc": "https://rpc-neutron.whispernode.com", "explorer": "https://mintscan.io/neutron", "currency": "NTRN"},
    {"id": "archway", "name": "Archway", "vm": "CosmWasm", "chainId": "archway-1", "status": "active", "rpc": "https://rpc.archway.io", "explorer": "https://mintscan.io/archway", "currency": "ARCH"},
    {"id": "stride", "name": "Stride", "vm": "CosmWasm", "chainId": "stride-1", "status": "active", "rpc": "https://rpc.stride.zone", "explorer": "https://mintscan.io/stride", "currency": "STRD"},
    {"id": "terra", "name": "Terra", "vm": "CosmWasm", "chainId": "phoenix-1", "status": "active", "rpc": "https://phoenix-lcd.terraclassic.community", "explorer": "https://finder.terra.money", "currency": "LUNA"},
    {"id": "juno", "name": "Juno", "vm": "CosmWasm", "chainId": "juno-1", "status": "active", "rpc": "https://juno-rpc.polkachu.com", "explorer": "https://mintscan.io/juno", "currency": "JUNO"},
    {"id": "stargaze", "name": "Stargaze", "vm": "CosmWasm", "chainId": "stargaze-1", "status": "indexing", "rpc": "https://rpc.stargaze.zone", "explorer": "https://www.mintscan.io/stargaze", "currency": "STARS"},
    # --- Substrate ---
    {"id": "polkadot", "name": "Polkadot", "vm": "Substrate", "chainId": 0, "status": "active", "rpc": "wss://rpc.polkadot.io", "explorer": "https://polkadot.subscan.io", "currency": "DOT"},
    {"id": "kusama", "name": "Kusama", "vm": "Substrate", "chainId": 2, "status": "active", "rpc": "wss://rpc.kusama.network", "explorer": "https://kusama.subscan.io", "currency": "KSM"},
    {"id": "astar-s", "name": "Astar (Substrate)", "vm": "Substrate", "chainId": 10, "status": "active", "rpc": "wss://rpc.astar.network", "explorer": "https://astar.subscan.io", "currency": "ASTR"},
    {"id": "acentrik", "name": "Acentrik", "vm": "Substrate", "chainId": 42, "status": "observation", "rpc": "wss://rpc.acentrik.io", "explorer": "https://explorer.acentrik.io", "currency": "ACK"},
    {"id": "bifrost", "name": "Bifrost", "vm": "Substrate", "chainId": 2030, "status": "active", "rpc": "wss://rpc.bifrost.io", "explorer": "https://bifrost.subscan.io", "currency": "BNC"},
    {"id": "phala", "name": "Phala Network", "vm": "Substrate", "chainId": 30, "status": "active", "rpc": "wss://rpc.phala.network", "explorer": "https://phala.subscan.io", "currency": "PHA"},
    {"id": "kilt-sub", "name": "KILT (Substrate)", "vm": "Substrate", "chainId": 109, "status": "active", "rpc": "wss://rpc.kilt.io", "explorer": "https://kilt.subscan.io", "currency": "KILT"},
    {"id": "hydradx", "name": "HydraDX", "vm": "Substrate", "chainId": 204, "status": "active", "rpc": "wss://rpc.hydradx.io", "explorer": "https://hydradx.subscan.io", "currency": "HDX"},
    # --- zkEVM ---
    {"id": "polygon-zk", "name": "Polygon zkEVM", "vm": "zkEVM", "chainId": 1101, "status": "active", "rpc": "https://zkevm-rpc.com", "explorer": "https://zkevm.polygonscan.com", "currency": "ETH"},
    {"id": "proof", "name": "Proof of Play", "vm": "zkEVM", "chainId": 1380012687, "status": "indexing", "rpc": "https://rpc.proofofplay.com", "explorer": "https://explorer.proofofplay.com", "currency": "POP"},
    {"id": "morphism", "name": "Morphism", "vm": "zkEVM", "chainId": 2818, "status": "active", "rpc": "https://rpc.morphism.xyz", "explorer": "https://explorer.morphism.xyz", "currency": "ETH"},
    {"id": "taiko", "name": "Taiko", "vm": "zkEVM", "chainId": 167000, "status": "active", "rpc": "https://rpc.taiko.xyz", "explorer": "https://explorer.taiko.xyz", "currency": "ETH"},
    {"id": "palm", "name": "Palm Network", "vm": "zkEVM", "chainId": 11297108109, "status": "active", "rpc": "https://palm-mainnet.publicnode.com", "explorer": "https://explorer.palm.io", "currency": "PALM"},
    # --- PVM (Parallel VM) ---
    {"id": "parallel", "name": "Parallel Finance", "vm": "PVM", "chainId": 106, "status": "active", "rpc": "https://rpc.parallel.fi", "explorer": "https://parallel.subscan.io", "currency": "PARA"},
    {"id": "acala", "name": "Acala", "vm": "PVM", "chainId": 787, "status": "active", "rpc": "https://rpc.acala.network", "explorer": "https://acala.subscan.io", "currency": "ACA"},
    {"id": "karura", "name": "Karura", "vm": "PVM", "chainId": 686, "status": "active", "rpc": "https://rpc.karura.network", "explorer": "https://karura.subscan.io", "currency": "KAR"},
    # --- Bitcoin Script ---
    {"id": "bitcoin", "name": "Bitcoin", "vm": "Bitcoin Script", "chainId": 0, "status": "active", "rpc": "https://blockstream.info/api", "explorer": "https://blockstream.info/btc", "currency": "BTC"},
    {"id": "dogecoin", "name": "Dogecoin", "vm": "Bitcoin Script", "chainId": 0, "status": "active", "rpc": "https://dogecoin-rpc.publicnode.com", "explorer": "https://dogechain.info", "currency": "DOGE"},
    {"id": "litecoin", "name": "Litecoin", "vm": "Bitcoin Script", "chainId": 0, "status": "active", "rpc": "https://litecoin-rpc.publicnode.com", "explorer": "https://litecoinscan.org", "currency": "LTC"},
    {"id": "bch", "name": "Bitcoin Cash", "vm": "Bitcoin Script", "chainId": 0, "status": "observation", "rpc": "https://bch-rpc.publicnode.com", "explorer": "https://blockchair.com/bitcoin-cash", "currency": "BCH"},
    # --- Lua (L1X) ---
    {"id": "l1x", "name": "L1X", "vm": "Lua", "chainId": 111, "status": "active", "rpc": "https://rpc.l1x.io", "explorer": "https://explorer.l1x.io", "currency": "L1X"},
    {"id": "l1x-testnet", "name": "L1X Testnet", "vm": "Lua", "chainId": 112, "status": "indexing", "rpc": "https://testnet-rpc.l1x.io", "explorer": "https://testnet.explorer.l1x.io", "currency": "L1X"},
    # --- Additional EVM appchains/L3s ---
    {"id": "degen", "name": "Degen Chain", "vm": "EVM", "chainId": 666666666, "status": "active", "rpc": "https://rpc.degen.tips", "explorer": "https://explorer.degen.tips", "currency": "DEGEN"},
    {"id": "redstone", "name": "Redstone", "vm": "EVM", "chainId": 690, "status": "active", "rpc": "https://rpc.redstonechain.com", "explorer": "https://explorer.redstone.xyz", "currency": "ETH"},
    {"id": "etherlink", "name": "Etherlink", "vm": "EVM", "chainId": 42793, "status": "active", "rpc": "https://rpc.etherlink.apexproto.xyz", "explorer": "https://explorer.etherlink.com", "currency": "XTZ"},
    {"id": "lyra", "name": "Lyra Chain", "vm": "EVM", "chainId": 957, "status": "indexing", "rpc": "https://rpc.lyra.finance", "explorer": "https://explorer.lyra.finance", "currency": "LYRA"},
    {"id": "xai", "name": "Xai", "vm": "EVM", "chainId": 660279, "status": "active", "rpc": "https://rpc.xai-chain.net", "explorer": "https://explorer.xai-chain.io", "currency": "XAI"},
    {"id": "aevo", "name": "Aevo", "vm": "EVM", "chainId": 54211, "status": "active", "rpc": "https://rpc.aevo.xyz", "explorer": "https://explorer.aevo.xyz", "currency": "AEVO"},
    {"id": "worldchain", "name": "World Chain", "vm": "EVM", "chainId": 480, "status": "active", "rpc": "https://rpc.worldchain.org", "explorer": "https://explorer.worldchain.org", "currency": "ETH"},
    {"id": "ronin", "name": "Ronin", "vm": "EVM", "chainId": 2020, "status": "active", "rpc": "https://rpc.ronin.chain.tf", "explorer": "https://explorer.roninchain.com", "currency": "RON"},
    {"id": "immutable-zk", "name": "Immutable zkEVM", "vm": "zkEVM", "chainId": 13371, "status": "active", "rpc": "https://rpc.immutable.com", "explorer": "https://explorer.immutable.com", "currency": "IMX"},
    {"id": "op-bnb", "name": "opBNB", "vm": "EVM", "chainId": 204, "status": "active", "rpc": "https://opbnb-rpc.publicnode.com", "explorer": "https://opbnb.bscscan.com", "currency": "BNB"},
    {"id": "megaeth", "name": "MegaETH", "vm": "EVM", "chainId": 53457, "status": "indexing", "rpc": "https://rpc.megaeth.io", "explorer": "https://explorer.megaeth.io", "currency": "ETH"},
    {"id": "initia", "name": "Initia", "vm": "CosmWasm", "chainId": "initia-1", "status": "active", "rpc": "https://rpc.initia.xyz", "explorer": "https://explorer.initia.xyz", "currency": "INIT"},
    {"id": "dymension", "name": "Dymension", "vm": "CosmWasm", "chainId": "dymension_1100-1", "status": "active", "rpc": "https://rpc.dymension.xyz", "explorer": "https://explorer.dymension.xyz", "currency": "DYM"},
    {"id": "mantra", "name": "MANTRA Chain", "vm": "CosmWasm", "chainId": "mantra-1", "status": "active", "rpc": "https://rpc.mantra.io", "explorer": "https://explorer.mantra.io", "currency": "OM"},
    {"id": "persistence", "name": "Persistence", "vm": "CosmWasm", "chainId": "core-1", "status": "indexing", "rpc": "https://rpc.persistence.one", "explorer": "https://explorer.persistence.one", "currency": "XPRT"},
    {"id": "0g", "name": "0G Network", "vm": "EVM", "chainId": 16602, "status": "active", "rpc": "https://rpc.0g.ai", "explorer": "https://explorer.0g.ai", "currency": "ZG"},
    {"id": "bevm", "name": "BEVM", "vm": "EVM", "chainId": 1151, "status": "active", "rpc": "https://rpc.bevm.io", "explorer": "https://scan.bevm.io", "currency": "BTC"},
    {"id": "merlin", "name": "Merlin Chain", "vm": "EVM", "chainId": 4200, "status": "active", "rpc": "https://rpc.merlinchain.io", "explorer": "https://explorer.merlinchain.io", "currency": "MERL"},
    {"id": "bsquared", "name": "B² Network", "vm": "zkEVM", "chainId": 223, "status": "active", "rpc": "https://rpc.bsquared.network", "explorer": "https://explorer.bsquared.network", "currency": "B2"},
    {"id": "zklink", "name": "zkLink Nova", "vm": "zkEVM", "chainId": 810180, "status": "active", "rpc": "https://rpc.zklink.io", "explorer": "https://explorer.zklink.io", "currency": "ETH"},
    {"id": "resilient", "name": "Resilient L2", "vm": "EVM", "chainId": 9999, "status": "observation", "rpc": "https://rpc.resilient.network", "explorer": "https://explorer.resilient.network", "currency": "RST"},
    {"id": "conduit", "name": "Conduit Chain", "vm": "EVM", "chainId": 7777, "status": "indexing", "rpc": "https://rpc.conduit.xyz", "explorer": "https://explorer.conduit.xyz", "currency": "CDT"},
    {"id": "story", "name": "Story Protocol", "vm": "EVM", "chainId": 1513, "status": "active", "rpc": "https://rpc.storyprotocol.io", "explorer": "https://explorer.storyprotocol.io", "currency": "IP"},
    {"id": "plume", "name": "Plume Network", "vm": "EVM", "chainId": 98866, "status": "active", "rpc": "https://rpc.plume.network", "explorer": "https://explorer.plume.network", "currency": "PLUME"},
    {"id": "viction", "name": "Viction", "vm": "EVM", "chainId": 88, "status": "active", "rpc": "https://rpc.viction.xyz", "explorer": "https://explorer.viction.xyz", "currency": "VIC"},
    {"id": "alvey", "name": "Alvey Chain", "vm": "EVM", "chainId": 188881, "status": "indexing", "rpc": "https://rpc.alveychain.com", "explorer": "https://explorer.alveychain.com", "currency": "ALV"},
    {"id": "cascadia", "name": "Cascadia", "vm": "EVM", "chainId": 4321, "status": "observation", "rpc": "https://rpc.cascadia.network", "explorer": "https://explorer.cascadia.network", "currency": "CASC"},
    {"id": "saga", "name": "Saga", "vm": "CosmWasm", "chainId": "saga-1", "status": "active", "rpc": "https://rpc.saga.xyz", "explorer": "https://explorer.saga.xyz", "currency": "SAGA"},
    {"id": "sei-cosm", "name": "Sei (CosmWasm)", "vm": "CosmWasm", "chainId": "sei-1", "status": "active", "rpc": "https://rpc.sei.io", "explorer": "https://sei.explorer.com", "currency": "SEI"},
    {"id": "noble", "name": "Noble", "vm": "CosmWasm", "chainId": "noble-1", "status": "active", "rpc": "https://rpc.noble.xyz", "explorer": "https://mintscan.io/noble", "currency": "USDC"},
    {"id": "celestia", "name": "Celestia", "vm": "CosmWasm", "chainId": "celestia-1", "status": "active", "rpc": "https://rpc.celestia.org", "explorer": "https://celestia.explorers.guru", "currency": "TIA"},
    {"id": "avail", "name": "Avail", "vm": "Substrate", "chainId": 1, "status": "indexing", "rpc": "wss://rpc.avail.so", "explorer": "https://explorer.avail.so", "currency": "AVAIL"},
    {"id": "manta-sub", "name": "Manta (Substrate)", "vm": "Substrate", "chainId": 77, "status": "active", "rpc": "wss://rpc.manta.systems", "explorer": "https://manta.subscan.io", "currency": "MANTA"},
    {"id": "aleph-zero", "name": "Aleph Zero", "vm": "Substrate", "chainId": 414, "status": "active", "rpc": "wss://rpc.alephzero.org", "explorer": "https://explorer.alephzero.org", "currency": "AZERO"},
    {"id": "zentry", "name": "Zentry", "vm": "EVM", "chainId": 6208, "status": "active", "rpc": "https://rpc.zentry.xyz", "explorer": "https://explorer.zentry.xyz", "currency": "ZENT"},
    {"id": "catizen", "name": "Catizen Chain", "vm": "EVM", "chainId": 2025, "status": "indexing", "rpc": "https://rpc.catizen.io", "explorer": "https://explorer.catizen.io", "currency": "CATI"},
    {"id": "qkvm", "name": "QKVM Quantum", "vm": "EVM", "chainId": 7799, "status": "observation", "rpc": "https://rpc.qkvm.io", "explorer": "https://explorer.qkvm.io", "currency": "QBIT"},
    {"id": "fuel", "name": "Fuel", "vm": "WASM", "chainId": 1, "status": "active", "rpc": "https://rpc.fuel.network", "explorer": "https://explorer.fuel.network", "currency": "FUEL"},
    {"id": "casper", "name": "Casper Network", "vm": "WASM", "chainId": 1, "status": "active", "rpc": "https://rpc.cspr.network", "explorer": "https://cspr.live", "currency": "CSPR"},
    {"id": "icp", "name": "Internet Computer", "vm": "WASM", "chainId": 0, "status": "active", "rpc": "https://icp-api.io", "explorer": "https://dashboard.internetcomputer.org", "currency": "ICP"},
    {"id": "hathor", "name": "Hathor Network", "vm": "Bitcoin Script", "chainId": 0, "status": "observation", "rpc": "https://rpc.hathor.network", "explorer": "https://explorer.hathor.network", "currency": "HTR"},
    {"id": "multibit", "name": "Multibit", "vm": "EVM", "chainId": 8889, "status": "indexing", "rpc": "https://rpc.multibit.io", "explorer": "https://explorer.multibit.io", "currency": "MUBI"},
    {"id": "berachain", "name": "Berachain", "vm": "EVM", "chainId": 80094, "status": "active", "rpc": "https://rpc.berachain.com", "explorer": "https://explorer.berachain.com", "currency": "BERA"},
    {"id": "monad", "name": "Monad", "vm": "EVM", "chainId": 10143, "status": "indexing", "rpc": "https://rpc.monad.xyz", "explorer": "https://explorer.monad.xyz", "currency": "MON"},
    {"id": "abstract", "name": "Abstract", "vm": "EVM", "chainId": 2741, "status": "active", "rpc": "https://rpc.abstract.xyz", "explorer": "https://explorer.abstract.xyz", "currency": "ETH"},
    {"id": "unichain", "name": "Unichain", "vm": "EVM", "chainId": 130, "status": "active", "rpc": "https://mainnet.unichain.org", "explorer": "https://explorer.unichain.org", "currency": "ETH"},
    {"id": "swell", "name": "Swell", "vm": "EVM", "chainId": 1923, "status": "indexing", "rpc": "https://rpc.swellnetwork.io", "explorer": "https://explorer.swellnetwork.io", "currency": "swETH"},
    {"id": "hemi", "name": "Hemi", "vm": "EVM", "chainId": 43111, "status": "active", "rpc": "https://rpc.hemi.xyz", "explorer": "https://explorer.hemi.xyz", "currency": "HEMI"},
    {"id": "corn", "name": "Corn", "vm": "EVM", "chainId": 21000001, "status": "active", "rpc": "https://rpc.corn.tech", "explorer": "https://explorer.corn.tech", "currency": "CORN"},
    {"id": "flow-evm", "name": "Flow EVM", "vm": "EVM", "chainId": 747, "status": "active", "rpc": "https://mainnet.evm.nodes.onflow.org", "explorer": "https://flowscan.org", "currency": "FLOW"},
]

VM_FAMILIES = [
    {"name": "EVM", "chains": 62, "totalContracts": 94000, "languages": ["Solidity", "Vyper", "Yul"]},
    {"name": "SVM", "chains": 5, "totalContracts": 3200, "languages": ["Rust", "C"]},
    {"name": "WASM", "chains": 8, "totalContracts": 4890, "languages": ["Rust", "AssemblyScript"]},
    {"name": "Cairo", "chains": 4, "totalContracts": 1260, "languages": ["Cairo"]},
    {"name": "Move", "chains": 4, "totalContracts": 940, "languages": ["Move"]},
    {"name": "TVM", "chains": 3, "totalContracts": 3100, "languages": ["FunC", "Tact"]},
    {"name": "CosmWasm", "chains": 15, "totalContracts": 4300, "languages": ["Rust"]},
    {"name": "Substrate", "chains": 12, "totalContracts": 2720, "languages": ["Rust"]},
    {"name": "zkEVM", "chains": 10, "totalContracts": 1890, "languages": ["Solidity", "ZoKrates"]},
    {"name": "PVM", "chains": 3, "totalContracts": 580, "languages": ["Rust"]},
    {"name": "Bitcoin Script", "chains": 5, "totalContracts": 295, "languages": ["Script"]},
    {"name": "Lua", "chains": 2, "totalContracts": 95, "languages": ["Lua"]},
]

CONTRACTS = [
    {"name": "TrionOracleV3", "language": "Solidity", "chain": "Arbitrum", "address": "0xb819c...58b3", "verified": True, "loc": 1847},
    {"name": "AkashicProof", "language": "Solidity", "chain": "0G Network", "address": "0xDB59...356d", "verified": True, "loc": 923},
    {"name": "TrionVaultV3", "language": "Solidity", "chain": "Arbitrum", "address": "0x93fD...716D", "verified": True, "loc": 1456},
    {"name": "BEOAttestation", "language": "Solidity", "chain": "Arbitrum", "address": "0x...", "verified": False, "loc": 672},
    {"name": "BIRPAttestation", "language": "Solidity", "chain": "Arbitrum", "address": "0x...", "verified": False, "loc": 534},
    {"name": "ExecutionGate", "language": "Solidity", "chain": "0G Network", "address": "0xDB59...356d", "verified": True, "loc": 891},
    {"name": "BTCFiGuard", "language": "Solidity", "chain": "Arbitrum", "address": "0x...", "verified": False, "loc": 445},
    {"name": "PriceAggregator", "language": "Vyper", "chain": "Arbitrum", "address": "0x...", "verified": True, "loc": 312},
    {"name": "SigmoidVault", "language": "Cairo", "chain": "StarkNet", "address": "0x...", "verified": True, "loc": 1203},
    {"name": "TrionSVM", "language": "Rust", "chain": "Solana", "address": "trion...prog", "verified": True, "loc": 2341},
    {"name": "NEARBridge", "language": "Rust", "chain": "NEAR", "address": "trion.near", "verified": True, "loc": 876},
    {"name": "TontinePool", "language": "FunC", "chain": "TON", "address": "EQC...", "verified": False, "loc": 567},
    {"name": "CosmosAdapter", "language": "Rust", "chain": "Cosmos", "address": "cosmos1...", "verified": True, "loc": 432},
    {"name": "SuiOracle", "language": "Move", "chain": "Sui", "address": "0x...", "verified": False, "loc": 389},
    {"name": "AptosGuard", "language": "Move", "chain": "Aptos", "address": "0x...", "verified": False, "loc": 298},
    {"name": "PolkadotPallet", "language": "Rust", "chain": "Polkadot", "address": "pallet::trion", "verified": True, "loc": 1567},
    {"name": "HskOracle", "language": "Solidity", "chain": "HashKey", "address": "0x...", "verified": True, "loc": 723},
    {"name": "ZkVerifier", "language": "Solidity", "chain": "zkSync", "address": "0x...", "verified": False, "loc": 654},
    {"name": "MantleAdapter", "language": "Solidity", "chain": "Mantle", "address": "0x...", "verified": False, "loc": 387},
    {"name": "ScrollBridge", "language": "Solidity", "chain": "Scroll", "address": "0x...", "verified": False, "loc": 445},
    {"name": "LineaProof", "language": "Solidity", "chain": "Linea", "address": "0x...", "verified": False, "loc": 312},
    {"name": "AnimaIndex", "language": "Solidity", "chain": "Arbitrum", "address": "0x...", "verified": False, "loc": 876},
    {"name": "CrisprEngine", "language": "Solidity", "chain": "Arbitrum", "address": "0x...", "verified": False, "loc": 1345},
    {"name": "BEOCore", "language": "Solidity", "chain": "Ethereum", "address": "0x...", "verified": False, "loc": 1567},
    {"name": "Falsifiability", "language": "Python", "chain": "Off-chain", "address": "offchain", "verified": True, "loc": 2341},
    {"name": "TrionBotOracle", "language": "Solidity", "chain": "BOT Chain", "address": "0xBOT...0001", "verified": True, "loc": 2156},
    {"name": "BotVaultV1", "language": "Solidity", "chain": "BOT Chain", "address": "0xBOT...0002", "verified": True, "loc": 1678},
    {"name": "BotChainBEO", "language": "Solidity", "chain": "BOT Chain", "address": "0xBOT...0003", "verified": True, "loc": 1234},
    {"name": "BotChainCRISPR", "language": "Solidity", "chain": "BOT Chain", "address": "0xBOT...0004", "verified": False, "loc": 1890},
    {"name": "BotChainPriceFeed", "language": "Solidity", "chain": "BOT Chain", "address": "0xBOT...0005", "verified": True, "loc": 567},
    {"name": "BotChainGovernance", "language": "Solidity", "chain": "BOT Chain", "address": "0xBOT...0006", "verified": False, "loc": 945},
]

RELAYERS = [
    {"name": "EVM Relayer", "status": "active", "chains": 7, "throughput": "12.4 tx/s", "lastPublish": "2s ago"},
    {"name": "Solana Relayer", "status": "active", "chains": 1, "throughput": "3.1 tx/s", "lastPublish": "5s ago"},
    {"name": "NEAR Relayer", "status": "active", "chains": 1, "throughput": "2.8 tx/s", "lastPublish": "8s ago"},
    {"name": "TON Relayer", "status": "standby", "chains": 1, "throughput": "0 tx/s", "lastPublish": "2m ago"},
    {"name": "0G DA Streamer", "status": "active", "chains": 1, "throughput": "1.2 MB/s", "lastPublish": "1s ago"},
    {"name": "StarkNet Relayer", "status": "active", "chains": 1, "throughput": "1.9 tx/s", "lastPublish": "12s ago"},
    {"name": "Cosmos Relayer", "status": "active", "chains": 1, "throughput": "0.7 tx/s", "lastPublish": "30s ago"},
    {"name": "BOT Chain Relayer", "status": "active", "chains": 1, "throughput": "2.1 tx/s", "lastPublish": "1s ago"},
]

DEPLOYMENTS = [
    {"name": "Arbitrum Sepolia", "env": "testnet", "status": "active", "contracts": 3, "url": "https://sepolia.arbiscan.io"},
    {"name": "0G Galileo Testnet", "env": "testnet", "status": "active", "contracts": 2, "url": "https://testnet.0g.ai"},
    {"name": "Solana Devnet", "env": "testnet", "status": "active", "contracts": 1, "url": "https://explorer.solana.com"},
    {"name": "Render Cloud", "env": "staging", "status": "active", "contracts": 0, "url": "https://trion.onrender.com"},
    {"name": "Arbitrum Mainnet", "env": "mainnet", "status": "pending", "contracts": 2, "url": "https://arbiscan.io"},
    {"name": "0G Mainnet", "env": "mainnet", "status": "pending", "contracts": 1, "url": "https://0g.ai"},
    {"name": "Ethereum Mainnet", "env": "mainnet", "status": "planned", "contracts": 1, "url": "https://etherscan.io"},
    {"name": "Solana Mainnet", "env": "mainnet", "status": "planned", "contracts": 1, "url": "https://explorer.solana.com"},
    {"name": "BOT Chain Mainnet", "env": "mainnet", "status": "active", "contracts": 6, "url": "https://scan.botchain.ai/"},
]

TRADING_PAIRS = [
    {"pair": "ETH/USD", "price": 3421.87, "change24h": 2.34, "volume24h": 18420000000, "firewall": "active", "btv": 3418.92},
    {"pair": "BTC/USD", "price": 67432.15, "change24h": -0.87, "volume24h": 32100000000, "firewall": "active", "btv": 67501.33},
    {"pair": "SOL/USD", "price": 172.43, "change24h": 5.12, "volume24h": 4230000000, "firewall": "monitoring", "btv": 171.88},
    {"pair": "ARB/USD", "price": 1.23, "change24h": 1.45, "volume24h": 892000000, "firewall": "active", "btv": 1.22},
    {"pair": "MATIC/USD", "price": 0.71, "change24h": -2.13, "volume24h": 567000000, "firewall": "active", "btv": 0.72},
    {"pair": "OP/USD", "price": 2.87, "change24h": 3.56, "volume24h": 423000000, "firewall": "monitoring", "btv": 2.85},
    {"pair": "BNB/USD", "price": 603.21, "change24h": 0.92, "volume24h": 1870000000, "firewall": "active", "btv": 602.45},
    {"pair": "AVAX/USD", "price": 38.56, "change24h": -1.78, "volume24h": 678000000, "firewall": "active", "btv": 38.89},
    {"pair": "BOT/USD", "price": 0.045, "change24h": 3.21, "volume24h": 12500000, "firewall": "active", "btv": 0.0448},
]

BEO_ENTITIES = [
    {"name": "Uniswap V3", "archetype": "AMM_NAVIGATOR", "coherence": 0.94, "mental": 0.88, "spiritual": 0.72, "status": "healthy", "chain": "Multi-chain"},
    {"name": "Aave V3", "archetype": "LIQUIDITY_GUARDIAN", "coherence": 0.91, "mental": 0.85, "spiritual": 0.68, "status": "healthy", "chain": "Multi-chain"},
    {"name": "Compound V3", "archetype": "RATE_ARBITRAGEUR", "coherence": 0.87, "mental": 0.79, "spiritual": 0.61, "status": "monitoring", "chain": "Ethereum"},
    {"name": "Lido", "archetype": "STAKING_ANCHOR", "coherence": 0.93, "mental": 0.91, "spiritual": 0.77, "status": "healthy", "chain": "Ethereum"},
    {"name": "Curve Finance", "archetype": "STABILITY_KEEPER", "coherence": 0.89, "mental": 0.82, "spiritual": 0.65, "status": "healthy", "chain": "Multi-chain"},
]

CRISPR_SIGNATURES = [
    {"id": "F1", "name": "Sandwich Attack", "pattern": "MEV_CAPTURE + SWAP + rapid reversal", "severity": "high", "intercepts": 1247},
    {"id": "F2", "name": "Flash Loan Manipulation", "pattern": "LEND + SWAP + REPAY within 1 block", "severity": "critical", "intercepts": 892},
    {"id": "F3", "name": "Oracle Manipulation", "pattern": "ORACLE_UPDATE + anomalous price delta", "severity": "critical", "intercepts": 634},
    {"id": "F4", "name": "Wash Trading", "pattern": "STAKE + cyclic SWAP patterns", "severity": "medium", "intercepts": 2341},
    {"id": "F5", "name": "Rug Pull Indicator", "pattern": "BURN + GOVERNANCE + liquidity withdrawal", "severity": "critical", "intercepts": 156},
    {"id": "F6", "name": "Front-Running", "pattern": "SWAP anticipation + MEV_CAPTURE", "severity": "high", "intercepts": 1876},
    {"id": "F7", "name": "Honeypot Detection", "pattern": "TRANSFER asymmetry + GOVERNANCE lock", "severity": "high", "intercepts": 423},
    {"id": "F8", "name": "Phishing Contract", "pattern": "APPROVE + untrusted TRANSFER target", "severity": "critical", "intercepts": 567},
    {"id": "F9", "name": "Gas Griefing", "pattern": "excessive GAS patterns + denial vectors", "severity": "low", "intercepts": 3456},
    {"id": "F10", "name": "Reentrancy Vector", "pattern": "CALL + state mutation before balance update", "severity": "critical", "intercepts": 234},
]

LIVING_SECURITY = [
    {"name": "CRISPR Engine", "status": "active", "score": 98.7, "uptime": "99.99%", "threats": 12},
    {"name": "Epigenetic Layer", "status": "active", "score": 95.2, "uptime": "99.97%", "threats": 3},
    {"name": "Immune Response", "status": "active", "score": 97.1, "uptime": "99.98%", "threats": 0},
    {"name": "Behavioral Firewall", "status": "active", "score": 96.8, "uptime": "99.95%", "threats": 5},
    {"name": "Adaptive Defense", "status": "monitoring", "score": 93.4, "uptime": "99.92%", "threats": 1},
    {"name": "ANIMA Correlation", "status": "active", "score": 94.6, "uptime": "99.90%", "threats": 2},
    {"name": "Self-Verification", "status": "active", "score": 99.1, "uptime": "99.99%", "threats": 0},
    {"name": "Falsifiability Engine", "status": "active", "score": 97.8, "uptime": "99.96%", "threats": 0},
]

GOVERNANCE_ITEMS = [
    {"id": "TIP-001", "title": "Deploy TrionOracle on Ethereum Mainnet", "status": "active", "votes_for": 1247, "votes_against": 89, "quorum": 0.78, "deadline": "2025-08-15"},
    {"id": "TIP-002", "title": "Integrate Sui Move VM indexer", "status": "active", "votes_for": 892, "votes_against": 156, "quorum": 0.62, "deadline": "2025-08-20"},
    {"id": "TIP-003", "title": "Upgrade CRISPR to v2 with adaptive signatures", "status": "passed", "votes_for": 2341, "votes_against": 23, "quorum": 0.95, "deadline": "2025-07-01"},
    {"id": "TIP-004", "title": "Add Bitcoin UTXO behavioral indexing", "status": "active", "votes_for": 678, "votes_against": 234, "quorum": 0.51, "deadline": "2025-09-01"},
    {"id": "TIP-005", "title": "ANIMA v3 - GitHub source crawler integration", "status": "passed", "votes_for": 1892, "votes_against": 45, "quorum": 0.88, "deadline": "2025-06-15"},
    {"id": "TIP-006", "title": "Zero-knowledge proof for signal publishing", "status": "discussion", "votes_for": 345, "votes_against": 123, "quorum": 0.34, "deadline": "2025-10-01"},
]

ANIMA_STREAMS = [
    {"name": "Behavioral Analysis", "status": "active", "throughput": "1.2K vectors/s", "accuracy": 0.94, "model": "FAISS + ANIMA v3"},
    {"name": "GitHub Source Intelligence", "status": "active", "throughput": "450 commits/s", "accuracy": 0.87, "model": "Source Crawler v2"},
    {"name": "Market Sentiment", "status": "active", "throughput": "5.6K signals/s", "accuracy": 0.91, "model": "BEO Analyzer"},
    {"name": "Cross-Chain Correlation", "status": "monitoring", "throughput": "800 pairs/s", "accuracy": 0.89, "model": "Phi-Sigma Engine"},
]

FALSIFIABILITY = [
    {"id": "F1", "name": "Coherence Threshold Test", "status": "passed", "lastRun": "2 min ago", "result": "C(t) > theta(t) for 99.7% of entities"},
    {"id": "F2", "name": "Signal Decay Verification", "status": "passed", "lastRun": "5 min ago", "result": "Half-life within expected range"},
    {"id": "F3", "name": "Cross-Chain Consistency", "status": "passed", "lastRun": "1 min ago", "result": "All chains within 2-sigma"},
    {"id": "F4", "name": "ANIMA Ground Truth", "status": "warning", "lastRun": "10 min ago", "result": "GitHub plane A=0.70 (neutral prior)"},
    {"id": "F5", "name": "CRISPR False Positive Rate", "status": "passed", "lastRun": "3 min ago", "result": "FPR < 0.001% over 10K signals"},
    {"id": "F6", "name": "BEO Behavioral Drift", "status": "passed", "lastRun": "8 min ago", "result": "No archetype shift detected"},
    {"id": "F7", "name": "Self-Verification Loop", "status": "passed", "lastRun": "30 sec ago", "result": "All 8 subsystems verified"},
]

ARCHETYPES = [
    {"name": "SAFE_HAVEN", "level": 1, "color": "#00D4AA", "desc": "Stable, predictable behavior"},
    {"name": "YIELD_FARMER", "level": 2, "color": "#00B894", "desc": "Consistent yield optimization"},
    {"name": "LIQUIDITY_PROVIDER", "level": 3, "color": "#6C5CE7", "desc": "Market-making behavior"},
    {"name": "TREND_FOLLOWER", "level": 4, "color": "#A29BFE", "desc": "Momentum-driven actions"},
    {"name": "ARBITRAGE_SEEKER", "level": 5, "color": "#FDCB6E", "desc": "Cross-venue price exploitation"},
    {"name": "WHALE_TRACKER", "level": 6, "color": "#F39C12", "desc": "Large entity monitoring"},
    {"name": "MEV_EXTRACTOR", "level": 7, "color": "#E17055", "desc": "Maximal extractable value"},
    {"name": "VOLATILE_ENTITY", "level": 8, "color": "#D63031", "desc": "Unpredictable behavior pattern"},
    {"name": "ADVERSARIAL_AGENT", "level": 9, "color": "#E84393", "desc": "Potentially hostile behavior"},
    {"name": "ATTACK_VECTOR", "level": 10, "color": "#FD79A8", "desc": "Confirmed attack signature"},
    {"name": "UNKNOWN_ANOMALY", "level": 11, "color": "#636E72", "desc": "Uncharacterized behavior"},
    {"name": "CRITICAL_THREAT", "level": 12, "color": "#2D3436", "desc": "Immediate threat detected"},
]

# ============================================================
# NEW DATA SECTIONS
# ============================================================

ZERO_BRIDGE_ROUTES = [
    {"routeId": "ZBR-001", "anchorChain": "Ethereum", "execChain": "Arbitrum", "routeType": "SPLIT", "btcpScore": 0.94, "gasSaved": 34.2, "beoContinuity": 0.97, "status": "active", "entity": "Uniswap V3", "assetIn": "ETH", "assetOut": "USDC", "value": 2450000},
    {"routeId": "ZBR-002", "anchorChain": "Ethereum", "execChain": "Optimism", "routeType": "NETTING", "btcpScore": 0.91, "gasSaved": 28.7, "beoContinuity": 0.95, "status": "active", "entity": "Aave V3", "assetIn": "USDC", "assetOut": "ETH", "value": 1820000},
    {"routeId": "ZBR-003", "anchorChain": "Ethereum", "execChain": "Base", "routeType": "SINGLE_CHAIN", "btcpScore": 0.88, "gasSaved": 41.5, "beoContinuity": 0.93, "status": "active", "entity": "Curve Finance", "assetIn": "ETH", "assetOut": "DAI", "value": 980000},
    {"routeId": "ZBR-004", "anchorChain": "Ethereum", "execChain": "Polygon", "routeType": "PARALLEL", "btcpScore": 0.86, "gasSaved": 52.1, "beoContinuity": 0.91, "status": "active", "entity": "Compound V3", "assetIn": "USDC", "assetOut": "MATIC", "value": 1540000},
    {"routeId": "ZBR-005", "anchorChain": "Ethereum", "execChain": "Solana", "routeType": "MULTIHOP", "btcpScore": 0.79, "gasSaved": 67.3, "beoContinuity": 0.84, "status": "completed", "entity": "Lido", "assetIn": "ETH", "assetOut": "SOL", "value": 3200000},
    {"routeId": "ZBR-006", "anchorChain": "Ethereum", "execChain": "Arbitrum", "routeType": "DEFERRED", "btcpScore": 0.92, "gasSaved": 38.9, "beoContinuity": 0.96, "status": "active", "entity": "Uniswap V3", "assetIn": "WBTC", "assetOut": "ETH", "value": 5600000},
    {"routeId": "ZBR-007", "anchorChain": "Arbitrum", "execChain": "BOT Chain", "routeType": "BITP", "btcpScore": 0.96, "gasSaved": 72.8, "beoContinuity": 0.99, "status": "active", "entity": "TrionBotOracle", "assetIn": "ETH", "assetOut": "BOT", "value": 450000},
    {"routeId": "ZBR-008", "anchorChain": "Ethereum", "execChain": "StarkNet", "routeType": "SPLIT", "btcpScore": 0.82, "gasSaved": 89.4, "beoContinuity": 0.88, "status": "pending", "entity": "SigmoidVault", "assetIn": "ETH", "assetOut": "STRK", "value": 780000},
    {"routeId": "ZBR-009", "anchorChain": "Solana", "execChain": "Ethereum", "routeType": "NETTING", "btcpScore": 0.77, "gasSaved": 23.1, "beoContinuity": 0.82, "status": "active", "entity": "TrionSVM", "assetIn": "SOL", "assetOut": "USDC", "value": 2100000},
    {"routeId": "ZBR-010", "anchorChain": "Ethereum", "execChain": "zkSync", "routeType": "PARALLEL", "btcpScore": 0.85, "gasSaved": 45.6, "beoContinuity": 0.90, "status": "active", "entity": "ZkVerifier", "assetIn": "ETH", "assetOut": "USDT", "value": 1340000},
    {"routeId": "ZBR-011", "anchorChain": "Ethereum", "execChain": "Scroll", "routeType": "MULTIHOP", "btcpScore": 0.83, "gasSaved": 51.2, "beoContinuity": 0.87, "status": "completed", "entity": "ScrollBridge", "assetIn": "ETH", "assetOut": "USDC", "value": 920000},
    {"routeId": "ZBR-012", "anchorChain": "Ethereum", "execChain": "Linea", "routeType": "SPLIT", "btcpScore": 0.80, "gasSaved": 47.8, "beoContinuity": 0.85, "status": "active", "entity": "LineaProof", "assetIn": "USDC", "assetOut": "ETH", "value": 670000},
    {"routeId": "ZBR-013", "anchorChain": "Ethereum", "execChain": "Mantle", "routeType": "DEFERRED", "btcpScore": 0.78, "gasSaved": 39.3, "beoContinuity": 0.83, "status": "pending", "entity": "MantleAdapter", "assetIn": "ETH", "assetOut": "MNT", "value": 540000},
    {"routeId": "ZBR-014", "anchorChain": "BNB Smart Chain", "execChain": "Ethereum", "routeType": "SINGLE_CHAIN", "btcpScore": 0.87, "gasSaved": 31.4, "beoContinuity": 0.92, "status": "active", "entity": "PancakeSwap", "assetIn": "BNB", "assetOut": "ETH", "value": 1890000},
    {"routeId": "ZBR-015", "anchorChain": "Ethereum", "execChain": "Avalanche", "routeType": "BITP", "btcpScore": 0.89, "gasSaved": 55.7, "beoContinuity": 0.93, "status": "active", "entity": "TraderJoe", "assetIn": "ETH", "assetOut": "AVAX", "value": 1120000},
    {"routeId": "ZBR-016", "anchorChain": "Ethereum", "execChain": "Sui", "routeType": "MULTIHOP", "btcpScore": 0.74, "gasSaved": 78.2, "beoContinuity": 0.79, "status": "pending", "entity": "SuiOracle", "assetIn": "ETH", "assetOut": "SUI", "value": 340000},
    {"routeId": "ZBR-017", "anchorChain": "Ethereum", "execChain": "NEAR", "routeType": "SPLIT", "btcpScore": 0.76, "gasSaved": 61.5, "beoContinuity": 0.81, "status": "active", "entity": "NEARBridge", "assetIn": "ETH", "assetOut": "NEAR", "value": 560000},
    {"routeId": "ZBR-018", "anchorChain": "Ethereum", "execChain": "Cosmos", "routeType": "NETTING", "btcpScore": 0.72, "gasSaved": 44.9, "beoContinuity": 0.77, "status": "active", "entity": "CosmosAdapter", "assetIn": "ETH", "assetOut": "ATOM", "value": 420000},
    {"routeId": "ZBR-019", "anchorChain": "Arbitrum", "execChain": "Solana", "routeType": "PARALLEL", "btcpScore": 0.81, "gasSaved": 69.3, "beoContinuity": 0.86, "status": "active", "entity": "Jupiter", "assetIn": "ARB", "assetOut": "SOL", "value": 780000},
    {"routeId": "ZBR-020", "anchorChain": "BOT Chain", "execChain": "Ethereum", "routeType": "BITP", "btcpScore": 0.97, "gasSaved": 82.1, "beoContinuity": 0.98, "status": "active", "entity": "BotChainBEO", "assetIn": "BOT", "assetOut": "ETH", "value": 230000},
    {"routeId": "ZBR-021", "anchorChain": "Ethereum", "execChain": "Base", "routeType": "SPLIT", "btcpScore": 0.90, "gasSaved": 36.7, "beoContinuity": 0.94, "status": "active", "entity": "Aerodrome", "assetIn": "ETH", "assetOut": "USDC", "value": 1670000},
    {"routeId": "ZBR-022", "anchorChain": "Ethereum", "execChain": "TON", "routeType": "MULTIHOP", "btcpScore": 0.68, "gasSaved": 73.6, "beoContinuity": 0.73, "status": "pending", "entity": "TontinePool", "assetIn": "ETH", "assetOut": "TON", "value": 290000},
]

ANNOTATORS = [
    {"annotatorId": "ANNOT-001", "stake": 15000, "accuracy": 0.967, "reviewsCompleted": 12450, "termStart": "2025-01-15", "termEnd": "2026-01-15", "jurisdiction": "Switzerland", "language": "English", "specialty": "MEV Detection", "status": "active"},
    {"annotatorId": "ANNOT-002", "stake": 12000, "accuracy": 0.943, "reviewsCompleted": 9870, "termStart": "2025-02-01", "termEnd": "2026-02-01", "jurisdiction": "Singapore", "language": "Mandarin", "specialty": "Oracle Manipulation", "status": "active"},
    {"annotatorId": "ANNOT-003", "stake": 8000, "accuracy": 0.921, "reviewsCompleted": 7650, "termStart": "2025-03-10", "termEnd": "2026-03-10", "jurisdiction": "Germany", "language": "German", "specialty": "Flash Loan Analysis", "status": "active"},
    {"annotatorId": "ANNOT-004", "stake": 20000, "accuracy": 0.981, "reviewsCompleted": 18200, "termStart": "2024-12-01", "termEnd": "2025-12-01", "jurisdiction": "United States", "language": "English", "specialty": "Behavioral Drift", "status": "active"},
    {"annotatorId": "ANNOT-005", "stake": 5000, "accuracy": 0.894, "reviewsCompleted": 4520, "termStart": "2025-04-15", "termEnd": "2026-04-15", "jurisdiction": "Japan", "language": "Japanese", "specialty": "Wash Trading", "status": "active"},
    {"annotatorId": "ANNOT-006", "stake": 18000, "accuracy": 0.956, "reviewsCompleted": 15670, "termStart": "2025-01-01", "termEnd": "2026-01-01", "jurisdiction": "Estonia", "language": "English", "specialty": "Rug Pull Detection", "status": "active"},
    {"annotatorId": "ANNOT-007", "stake": 7000, "accuracy": 0.878, "reviewsCompleted": 3410, "termStart": "2025-05-01", "termEnd": "2026-05-01", "jurisdiction": "South Korea", "language": "Korean", "specialty": "Cross-Chain Fraud", "status": "active"},
    {"annotatorId": "ANNOT-008", "stake": 25000, "accuracy": 0.992, "reviewsCompleted": 22100, "termStart": "2024-10-01", "termEnd": "2025-10-01", "jurisdiction": "United Kingdom", "language": "English", "specialty": "Reentrancy Analysis", "status": "recused"},
    {"annotatorId": "ANNOT-009", "stake": 3000, "accuracy": 0.845, "reviewsCompleted": 2190, "termStart": "2024-06-01", "termEnd": "2025-06-01", "jurisdiction": "Brazil", "language": "Portuguese", "specialty": "Phishing Detection", "status": "expired"},
    {"annotatorId": "ANNOT-010", "stake": 11000, "accuracy": 0.935, "reviewsCompleted": 8940, "termStart": "2025-02-15", "termEnd": "2026-02-15", "jurisdiction": "Netherlands", "language": "Dutch", "specialty": "Gas Optimization", "status": "active"},
    {"annotatorId": "ANNOT-011", "stake": 9000, "accuracy": 0.918, "reviewsCompleted": 6780, "termStart": "2025-03-01", "termEnd": "2026-03-01", "jurisdiction": "Canada", "language": "English", "specialty": "DeFi Risk Assessment", "status": "active"},
    {"annotatorId": "ANNOT-012", "stake": 14000, "accuracy": 0.952, "reviewsCompleted": 11230, "termStart": "2025-01-20", "termEnd": "2026-01-20", "jurisdiction": "Australia", "language": "English", "specialty": "NFT Behavioral Analysis", "status": "active"},
    {"annotatorId": "ANNOT-013", "stake": 6500, "accuracy": 0.901, "reviewsCompleted": 5340, "termStart": "2025-04-01", "termEnd": "2026-04-01", "jurisdiction": "India", "language": "Hindi", "specialty": "Stablecoin Depeg", "status": "active"},
    {"annotatorId": "ANNOT-014", "stake": 22000, "accuracy": 0.976, "reviewsCompleted": 19870, "termStart": "2024-11-15", "termEnd": "2025-11-15", "jurisdiction": "Liechtenstein", "language": "German", "specialty": "Front-Running", "status": "active"},
    {"annotatorId": "ANNOT-015", "stake": 4500, "accuracy": 0.867, "reviewsCompleted": 2890, "termStart": "2025-05-15", "termEnd": "2026-05-15", "jurisdiction": "UAE", "language": "Arabic", "specialty": "Bridge Exploit Analysis", "status": "active"},
    {"annotatorId": "ANNOT-016", "stake": 16000, "accuracy": 0.961, "reviewsCompleted": 13450, "termStart": "2025-01-10", "termEnd": "2026-01-10", "jurisdiction": "Switzerland", "language": "French", "specialty": "Honeypot Detection", "status": "active"},
]

VALIDATORS = [
    {"validatorId": "VAL-001", "stake": 450000, "diversity": 0.92, "effectiveWeight": 0.088, "architecture": "EVM", "region": "us-east", "jurisdiction": "United States", "uptime": 99.97, "lastVote": "3s ago", "status": "active"},
    {"validatorId": "VAL-002", "stake": 380000, "diversity": 0.89, "effectiveWeight": 0.079, "architecture": "SVM", "region": "us-west", "jurisdiction": "United States", "uptime": 99.94, "lastVote": "5s ago", "status": "active"},
    {"validatorId": "VAL-003", "stake": 520000, "diversity": 0.95, "effectiveWeight": 0.094, "architecture": "Cosmos", "region": "eu-west", "jurisdiction": "Germany", "uptime": 99.99, "lastVote": "2s ago", "status": "active"},
    {"validatorId": "VAL-004", "stake": 290000, "diversity": 0.84, "effectiveWeight": 0.067, "architecture": "EVM", "region": "eu-north", "jurisdiction": "Finland", "uptime": 99.91, "lastVote": "8s ago", "status": "active"},
    {"validatorId": "VAL-005", "stake": 610000, "diversity": 0.97, "effectiveWeight": 0.102, "architecture": "Substrate", "region": "ap-east", "jurisdiction": "Singapore", "uptime": 99.98, "lastVote": "1s ago", "status": "active"},
    {"validatorId": "VAL-006", "stake": 340000, "diversity": 0.86, "effectiveWeight": 0.073, "architecture": "Cairo", "region": "eu-central", "jurisdiction": "Switzerland", "uptime": 99.95, "lastVote": "4s ago", "status": "active"},
    {"validatorId": "VAL-007", "stake": 410000, "diversity": 0.91, "effectiveWeight": 0.084, "architecture": "Move", "region": "ap-south", "jurisdiction": "India", "uptime": 99.88, "lastVote": "7s ago", "status": "active"},
    {"validatorId": "VAL-008", "stake": 270000, "diversity": 0.81, "effectiveWeight": 0.062, "architecture": "WASM", "region": "ap-northeast", "jurisdiction": "Japan", "uptime": 99.93, "lastVote": "6s ago", "status": "active"},
    {"validatorId": "VAL-009", "stake": 180000, "diversity": 0.73, "effectiveWeight": 0.045, "architecture": "TVM", "region": "eu-east", "jurisdiction": "Ukraine", "uptime": 98.50, "lastVote": "45s ago", "status": "slashed"},
    {"validatorId": "VAL-010", "stake": 490000, "diversity": 0.94, "effectiveWeight": 0.091, "architecture": "EVM", "region": "us-central", "jurisdiction": "United States", "uptime": 99.96, "lastVote": "2s ago", "status": "active"},
    {"validatorId": "VAL-011", "stake": 350000, "diversity": 0.87, "effectiveWeight": 0.075, "architecture": "zkEVM", "region": "eu-west", "jurisdiction": "Ireland", "uptime": 99.92, "lastVote": "5s ago", "status": "active"},
    {"validatorId": "VAL-012", "stake": 420000, "diversity": 0.93, "effectiveWeight": 0.086, "architecture": "Cosmos", "region": "sa-east", "jurisdiction": "Brazil", "uptime": 99.89, "lastVote": "9s ago", "status": "active"},
    {"validatorId": "VAL-013", "stake": 310000, "diversity": 0.85, "effectiveWeight": 0.069, "architecture": "EVM", "region": "af-south", "jurisdiction": "South Africa", "uptime": 99.78, "lastVote": "12s ago", "status": "active"},
    {"validatorId": "VAL-014", "stake": 560000, "diversity": 0.96, "effectiveWeight": 0.098, "architecture": "Substrate", "region": "ap-southeast", "jurisdiction": "Australia", "uptime": 99.97, "lastVote": "1s ago", "status": "active"},
    {"validatorId": "VAL-015", "stake": 230000, "diversity": 0.79, "effectiveWeight": 0.056, "architecture": "Bitcoin Script", "region": "us-west", "jurisdiction": "Canada", "uptime": 99.85, "lastVote": "15s ago", "status": "active"},
    {"validatorId": "VAL-016", "stake": 480000, "diversity": 0.93, "effectiveWeight": 0.089, "architecture": "PVM", "region": "eu-north", "jurisdiction": "Sweden", "uptime": 99.94, "lastVote": "3s ago", "status": "active"},
    {"validatorId": "VAL-017", "stake": 150000, "diversity": 0.68, "effectiveWeight": 0.038, "architecture": "Lua", "region": "me-south", "jurisdiction": "UAE", "uptime": 97.20, "lastVote": "2m ago", "status": "inactive"},
    {"validatorId": "VAL-018", "stake": 390000, "diversity": 0.88, "effectiveWeight": 0.080, "architecture": "EVM", "region": "ap-east", "jurisdiction": "Hong Kong", "uptime": 99.91, "lastVote": "4s ago", "status": "active"},
    {"validatorId": "VAL-019", "stake": 330000, "diversity": 0.86, "effectiveWeight": 0.072, "architecture": "SVM", "region": "us-east", "jurisdiction": "United States", "uptime": 99.90, "lastVote": "6s ago", "status": "active"},
    {"validatorId": "VAL-020", "stake": 440000, "diversity": 0.92, "effectiveWeight": 0.087, "architecture": "Move", "region": "eu-central", "jurisdiction": "Netherlands", "uptime": 99.93, "lastVote": "3s ago", "status": "active"},
    {"validatorId": "VAL-021", "stake": 370000, "diversity": 0.87, "effectiveWeight": 0.076, "architecture": "Cairo", "region": "me-north", "jurisdiction": "Israel", "uptime": 99.87, "lastVote": "8s ago", "status": "active"},
    {"validatorId": "VAL-022", "stake": 500000, "diversity": 0.95, "effectiveWeight": 0.096, "architecture": "Cosmos", "region": "ap-south", "jurisdiction": "Singapore", "uptime": 99.98, "lastVote": "1s ago", "status": "active"},
    {"validatorId": "VAL-023", "stake": 260000, "diversity": 0.82, "effectiveWeight": 0.060, "architecture": "WASM", "region": "eu-west", "jurisdiction": "United Kingdom", "uptime": 99.86, "lastVote": "10s ago", "status": "active"},
    {"validatorId": "VAL-024", "stake": 200000, "diversity": 0.75, "effectiveWeight": 0.048, "architecture": "TVM", "region": "eu-east", "jurisdiction": "Turkey", "uptime": 99.10, "lastVote": "30s ago", "status": "active"},
    {"validatorId": "VAL-025", "stake": 470000, "diversity": 0.94, "effectiveWeight": 0.090, "architecture": "zkEVM", "region": "us-central", "jurisdiction": "United States", "uptime": 99.95, "lastVote": "2s ago", "status": "active"},
    {"validatorId": "VAL-026", "stake": 360000, "diversity": 0.88, "effectiveWeight": 0.077, "architecture": "EVM", "region": "sa-east", "jurisdiction": "Argentina", "uptime": 99.82, "lastVote": "11s ago", "status": "active"},
    {"validatorId": "VAL-027", "stake": 300000, "diversity": 0.83, "effectiveWeight": 0.065, "architecture": "Substrate", "region": "ap-northeast", "jurisdiction": "South Korea", "uptime": 99.88, "lastVote": "7s ago", "status": "active"},
]

EVOLUTIONARY_FITNESS = [
    {"componentId": "FIT-001", "name": "BEO Core Engine", "pa": 0.94, "ice": 0.87, "as": 0.91, "love": 0.82, "fitness": 0.885, "im": 0.79, "status": "optimal"},
    {"componentId": "FIT-002", "name": "CRISPR v2", "pa": 0.97, "ice": 0.92, "as": 0.88, "love": 0.76, "fitness": 0.882, "im": 0.85, "status": "optimal"},
    {"componentId": "FIT-003", "name": "ANIMA v3 Analyzer", "pa": 0.89, "ice": 0.84, "as": 0.93, "love": 0.71, "fitness": 0.842, "im": 0.72, "status": "healthy"},
    {"componentId": "FIT-004", "name": "Zero Bridge Router", "pa": 0.91, "ice": 0.79, "as": 0.86, "love": 0.89, "fitness": 0.862, "im": 0.81, "status": "optimal"},
    {"componentId": "FIT-005", "name": "Akashic Index", "pa": 0.86, "ice": 0.95, "as": 0.78, "love": 0.68, "fitness": 0.818, "im": 0.74, "status": "healthy"},
    {"componentId": "FIT-006", "name": "Falsifiability Engine", "pa": 0.99, "ice": 0.88, "as": 0.72, "love": 0.91, "fitness": 0.875, "im": 0.90, "status": "optimal"},
    {"componentId": "FIT-007", "name": "Behavioral Firewall", "pa": 0.92, "ice": 0.81, "as": 0.94, "love": 0.73, "fitness": 0.850, "im": 0.78, "status": "healthy"},
    {"componentId": "FIT-008", "name": "Epigenetic Layer", "pa": 0.85, "ice": 0.90, "as": 0.80, "love": 0.94, "fitness": 0.873, "im": 0.82, "status": "optimal"},
    {"componentId": "FIT-009", "name": "Continuum DEX Engine", "pa": 0.88, "ice": 0.76, "as": 0.95, "love": 0.65, "fitness": 0.810, "im": 0.71, "status": "adapting"},
    {"componentId": "FIT-010", "name": "Immune Response System", "pa": 0.93, "ice": 0.83, "as": 0.89, "love": 0.87, "fitness": 0.880, "im": 0.84, "status": "optimal"},
    {"componentId": "FIT-011", "name": "TRION-BFT Consensus", "pa": 0.96, "ice": 0.91, "as": 0.77, "love": 0.83, "fitness": 0.867, "im": 0.88, "status": "optimal"},
    {"componentId": "FIT-012", "name": "Genomic Key Manager", "pa": 0.90, "ice": 0.94, "as": 0.82, "love": 0.79, "fitness": 0.863, "im": 0.83, "status": "healthy"},
]

SBA_DATA = [
    {"nation": "Switzerland", "institutionalQuality": 0.96, "informationIntegrity": 0.93, "socialStability": 0.97, "governanceBehavior": 0.95, "capitalFreedom": 0.91, "sbaScore": 0.944, "trend": "stable"},
    {"nation": "Singapore", "institutionalQuality": 0.94, "informationIntegrity": 0.91, "socialStability": 0.93, "governanceBehavior": 0.95, "capitalFreedom": 0.89, "sbaScore": 0.924, "trend": "improving"},
    {"nation": "United States", "institutionalQuality": 0.87, "informationIntegrity": 0.78, "socialStability": 0.72, "governanceBehavior": 0.80, "capitalFreedom": 0.92, "sbaScore": 0.818, "trend": "declining"},
    {"nation": "Estonia", "institutionalQuality": 0.91, "informationIntegrity": 0.89, "socialStability": 0.90, "governanceBehavior": 0.88, "capitalFreedom": 0.86, "sbaScore": 0.888, "trend": "improving"},
    {"nation": "Germany", "institutionalQuality": 0.90, "informationIntegrity": 0.85, "socialStability": 0.86, "governanceBehavior": 0.87, "capitalFreedom": 0.82, "sbaScore": 0.860, "trend": "stable"},
    {"nation": "Japan", "institutionalQuality": 0.89, "informationIntegrity": 0.86, "socialStability": 0.88, "governanceBehavior": 0.84, "capitalFreedom": 0.80, "sbaScore": 0.854, "trend": "stable"},
    {"nation": "United Kingdom", "institutionalQuality": 0.88, "informationIntegrity": 0.83, "socialStability": 0.81, "governanceBehavior": 0.85, "capitalFreedom": 0.87, "sbaScore": 0.848, "trend": "declining"},
    {"nation": "South Korea", "institutionalQuality": 0.86, "informationIntegrity": 0.82, "socialStability": 0.79, "governanceBehavior": 0.83, "capitalFreedom": 0.84, "sbaScore": 0.828, "trend": "improving"},
    {"nation": "UAE", "institutionalQuality": 0.83, "informationIntegrity": 0.76, "socialStability": 0.85, "governanceBehavior": 0.78, "capitalFreedom": 0.88, "sbaScore": 0.820, "trend": "improving"},
    {"nation": "Nigeria", "institutionalQuality": 0.52, "informationIntegrity": 0.48, "socialStability": 0.55, "governanceBehavior": 0.50, "capitalFreedom": 0.62, "sbaScore": 0.534, "trend": "improving"},
    {"nation": "India", "institutionalQuality": 0.71, "informationIntegrity": 0.64, "socialStability": 0.68, "governanceBehavior": 0.66, "capitalFreedom": 0.72, "sbaScore": 0.682, "trend": "improving"},
    {"nation": "Brazil", "institutionalQuality": 0.65, "informationIntegrity": 0.58, "socialStability": 0.60, "governanceBehavior": 0.62, "capitalFreedom": 0.68, "sbaScore": 0.626, "trend": "stable"},
]

BIBL_DATA = [
    {"chain": "Ethereum", "nlScore": 0.912, "gasForecast": 34.5, "ccCoherence": 0.887, "mfScore": 0.023, "blockCapacity": 0.78, "finalityDist": 12.4, "beoState": "COHERENT", "timestamp": "2025-07-14T12:00:00Z"},
    {"chain": "Arbitrum", "nlScore": 0.894, "gasForecast": 0.12, "ccCoherence": 0.901, "mfScore": 0.031, "blockCapacity": 0.62, "finalityDist": 0.25, "beoState": "COHERENT", "timestamp": "2025-07-14T12:01:00Z"},
    {"chain": "Solana", "nlScore": 0.876, "gasForecast": 0.00025, "ccCoherence": 0.862, "mfScore": 0.018, "blockCapacity": 0.91, "finalityDist": 0.4, "beoState": "COHERENT", "timestamp": "2025-07-14T12:02:00Z"},
    {"chain": "Optimism", "nlScore": 0.889, "gasForecast": 0.08, "ccCoherence": 0.878, "mfScore": 0.042, "blockCapacity": 0.55, "finalityDist": 2.0, "beoState": "WARNING", "timestamp": "2025-07-14T12:03:00Z"},
    {"chain": "Base", "nlScore": 0.901, "gasForecast": 0.06, "ccCoherence": 0.912, "mfScore": 0.015, "blockCapacity": 0.70, "finalityDist": 2.0, "beoState": "COHERENT", "timestamp": "2025-07-14T12:04:00Z"},
    {"chain": "StarkNet", "nlScore": 0.834, "gasForecast": 0.003, "ccCoherence": 0.845, "mfScore": 0.056, "blockCapacity": 0.45, "finalityDist": 0.1, "beoState": "MONITORING", "timestamp": "2025-07-14T12:05:00Z"},
    {"chain": "Polygon", "nlScore": 0.867, "gasForecast": 0.04, "ccCoherence": 0.856, "mfScore": 0.038, "blockCapacity": 0.68, "finalityDist": 2.1, "beoState": "COHERENT", "timestamp": "2025-07-14T12:06:00Z"},
    {"chain": "zkSync Era", "nlScore": 0.845, "gasForecast": 0.01, "ccCoherence": 0.838, "mfScore": 0.047, "blockCapacity": 0.52, "finalityDist": 0.5, "beoState": "WARNING", "timestamp": "2025-07-14T12:07:00Z"},
    {"chain": "BOT Chain", "nlScore": 0.943, "gasForecast": 0.005, "ccCoherence": 0.967, "mfScore": 0.008, "blockCapacity": 0.82, "finalityDist": 1.5, "beoState": "COHERENT", "timestamp": "2025-07-14T12:08:00Z"},
    {"chain": "Sui", "nlScore": 0.823, "gasForecast": 0.001, "ccCoherence": 0.812, "mfScore": 0.061, "blockCapacity": 0.88, "finalityDist": 0.6, "beoState": "MONITORING", "timestamp": "2025-07-14T12:09:00Z"},
]

AKASHIC_INDEX_DATA = {
    "totalBHEntities": 2847561,
    "totalBHGenerated": 145892340,
    "depthScore": 0.8923,
    "faissIndexSize": "4.7 GB",
    "vectorsIndexed": 18475623,
    "queryLatency": 12.4,
    "storageUsed": "127.3 GB",
    "appendRate": 2340.5,
    "oldestRecord": "2024-01-15T00:00:00Z",
    "newestRecord": "2025-07-14T12:00:00Z",
    "convergenceStatus": "converging",
}

CONTINUUM_DEX = [
    {"pair": "ETH-BEHAVIORAL/USDC", "bidScore": 0.91, "complementScore": 0.87, "pmoPrice": 3481.23, "ccpPremium": 1.023, "settlementStatus": "settled", "btcpRouteId": "ZBR-001", "gasSaved": 34.2, "bothParties": True, "entityA": "Uniswap V3", "entityB": "Aave V3"},
    {"pair": "BTC-SIGMA/USDT", "bidScore": 0.88, "complementScore": 0.92, "pmoPrice": 68123.45, "ccpPremium": 1.015, "settlementStatus": "settled", "btcpRouteId": "ZBR-005", "gasSaved": 67.3, "bothParties": True, "entityA": "Lido", "entityB": "Curve Finance"},
    {"pair": "SOL-ANIMA/USDC", "bidScore": 0.84, "complementScore": 0.79, "pmoPrice": 174.56, "ccpPremium": 0.987, "settlementStatus": "pending", "btcpRouteId": "ZBR-009", "gasSaved": 23.1, "bothParties": False, "entityA": "TrionSVM", "entityB": "Jupiter"},
    {"pair": "ARB-COHERENCE/ETH", "bidScore": 0.93, "complementScore": 0.90, "pmoPrice": 1.245, "ccpPremium": 1.034, "settlementStatus": "settled", "btcpRouteId": "ZBR-001", "gasSaved": 34.2, "bothParties": True, "entityA": "Uniswap V3", "entityB": "Compound V3"},
    {"pair": "BOT-GENOME/USDC", "bidScore": 0.97, "complementScore": 0.95, "pmoPrice": 0.046, "ccpPremium": 1.067, "settlementStatus": "settled", "btcpRouteId": "ZBR-007", "gasSaved": 72.8, "bothParties": True, "entityA": "TrionBotOracle", "entityB": "BotChainBEO"},
    {"pair": "ETH-FITNESS/DAI", "bidScore": 0.86, "complementScore": 0.81, "pmoPrice": 3398.12, "ccpPremium": 0.998, "settlementStatus": "pending", "btcpRouteId": "ZBR-003", "gasSaved": 41.5, "bothParties": False, "entityA": "Curve Finance", "entityB": "Aave V3"},
    {"pair": "MATIC-BEHAVIORAL/USDT", "bidScore": 0.82, "complementScore": 0.78, "pmoPrice": 0.708, "ccpPremium": 1.005, "settlementStatus": "settled", "btcpRouteId": "ZBR-004", "gasSaved": 52.1, "bothParties": True, "entityA": "Compound V3", "entityB": "QuickSwap"},
    {"pair": "AVAX-SIGMA/USDC", "bidScore": 0.89, "complementScore": 0.85, "pmoPrice": 39.12, "ccpPremium": 1.019, "settlementStatus": "settled", "btcpRouteId": "ZBR-015", "gasSaved": 55.7, "bothParties": True, "entityA": "TraderJoe", "entityB": "Pangolin"},
    {"pair": "NEAR-ANIMA/ETH", "bidScore": 0.79, "complementScore": 0.74, "pmoPrice": 5.23, "ccpPremium": 0.976, "settlementStatus": "pending", "btcpRouteId": "ZBR-017", "gasSaved": 61.5, "bothParties": False, "entityA": "NEARBridge", "entityB": "Ref Finance"},
    {"pair": "ETH-LOVE/USDC", "bidScore": 0.95, "complementScore": 0.93, "pmoPrice": 3456.78, "ccpPremium": 1.041, "settlementStatus": "settled", "btcpRouteId": "ZBR-006", "gasSaved": 38.9, "bothParties": True, "entityA": "Uniswap V3", "entityB": "Lido"},
    {"pair": "SUI-COHERENCE/USDC", "bidScore": 0.77, "complementScore": 0.72, "pmoPrice": 3.45, "ccpPremium": 0.962, "settlementStatus": "pending", "btcpRouteId": "ZBR-016", "gasSaved": 78.2, "bothParties": False, "entityA": "SuiOracle", "entityB": "Turbos"},
    {"pair": "TON-BEHAVIORAL/ETH", "bidScore": 0.71, "complementScore": 0.68, "pmoPrice": 6.89, "ccpPremium": 0.945, "settlementStatus": "pending", "btcpRouteId": "ZBR-022", "gasSaved": 73.6, "bothParties": False, "entityA": "TontinePool", "entityB": "DeDust"},
    {"pair": "ATOM-ANIMA/USDC", "bidScore": 0.83, "complementScore": 0.80, "pmoPrice": 8.92, "ccpPremium": 1.008, "settlementStatus": "settled", "btcpRouteId": "ZBR-018", "gasSaved": 44.9, "bothParties": True, "entityA": "CosmosAdapter", "entityB": "Osmosis"},
    {"pair": "DOT-FITNESS/USDT", "bidScore": 0.85, "complementScore": 0.82, "pmoPrice": 7.12, "ccpPremium": 1.012, "settlementStatus": "settled", "btcpRouteId": "ZBR-014", "gasSaved": 31.4, "bothParties": True, "entityA": "PolkadotPallet", "entityB": "Acala"},
    {"pair": "OP-SIGMA/ETH", "bidScore": 0.90, "complementScore": 0.88, "pmoPrice": 2.91, "ccpPremium": 1.027, "settlementStatus": "settled", "btcpRouteId": "ZBR-002", "gasSaved": 28.7, "bothParties": True, "entityA": "Aave V3", "entityB": "Velodrome"},
]

BEHAVIORAL_MARKETPLACE = [
    {"listingId": "BML-001", "dataType": "behavioral_feed", "provider": "TRION Core", "price": 500, "buyers": 234, "rating": 4.87, "dataPoints": 45000000, "freshness": "1.2s", "chain": "Multi-chain"},
    {"listingId": "BML-002", "dataType": "akashic_snapshot", "provider": "Akashic Labs", "price": 1200, "buyers": 89, "rating": 4.92, "dataPoints": 18475623, "freshness": "5.0s", "chain": "Arbitrum"},
    {"listingId": "BML-003", "dataType": "anima_intelligence", "provider": "ANIMA Network", "price": 800, "buyers": 156, "rating": 4.79, "dataPoints": 28000000, "freshness": "0.8s", "chain": "Ethereum"},
    {"listingId": "BML-004", "dataType": "btc_proof", "provider": "Zero Bridge", "price": 2000, "buyers": 45, "rating": 4.95, "dataPoints": 8900000, "freshness": "12.0s", "chain": "Ethereum"},
    {"listingId": "BML-005", "dataType": "behavioral_feed", "provider": "Solana Analytics", "price": 350, "buyers": 312, "rating": 4.65, "dataPoints": 12000000, "freshness": "0.4s", "chain": "Solana"},
    {"listingId": "BML-006", "dataType": "akashic_snapshot", "provider": "BOT Chain Intel", "price": 600, "buyers": 78, "rating": 4.83, "dataPoints": 5600000, "freshness": "2.1s", "chain": "BOT Chain"},
    {"listingId": "BML-007", "dataType": "anima_intelligence", "provider": "StarkNet Oracle", "price": 950, "buyers": 67, "rating": 4.71, "dataPoints": 3400000, "freshness": "3.5s", "chain": "StarkNet"},
    {"listingId": "BML-008", "dataType": "btc_proof", "provider": "BTC Fi Guard", "price": 1500, "buyers": 34, "rating": 4.89, "dataPoints": 2100000, "freshness": "8.7s", "chain": "Bitcoin"},
    {"listingId": "BML-009", "dataType": "behavioral_feed", "provider": "Cosmos Indexer", "price": 280, "buyers": 189, "rating": 4.58, "dataPoints": 7800000, "freshness": "1.8s", "chain": "Cosmos"},
    {"listingId": "BML-010", "dataType": "akashic_snapshot", "provider": "Move Analytics", "price": 750, "buyers": 52, "rating": 4.76, "dataPoints": 4100000, "freshness": "4.2s", "chain": "Sui"},
    {"listingId": "BML-011", "dataType": "anima_intelligence", "provider": "TON Intelligence", "price": 420, "buyers": 98, "rating": 4.62, "dataPoints": 2900000, "freshness": "6.3s", "chain": "TON"},
    {"listingId": "BML-012", "dataType": "btc_proof", "provider": "zkSync Verifier", "price": 1800, "buyers": 28, "rating": 4.91, "dataPoints": 1500000, "freshness": "15.2s", "chain": "zkSync Era"},
]

GENOMIC_KEYS = [
    {"entityId": "ENT-UNISWAP", "generation": 1247, "sense": "a3f8d2e1", "antisense": "7b2c9e4f", "complementValid": True, "eventsAbsorbed": 4523000, "causalDepth": 12.4, "lastEvolution": "2025-07-14T11:58:00Z", "securityBound": 0.997},
    {"entityId": "ENT-AAVE", "generation": 1102, "sense": "d4c7b1a9", "antisense": "8e5f3d2c", "complementValid": True, "eventsAbsorbed": 3891000, "causalDepth": 11.8, "lastEvolution": "2025-07-14T11:56:00Z", "securityBound": 0.994},
    {"entityId": "ENT-COMPOUND", "generation": 987, "sense": "b6e9a2d4", "antisense": "1c3f7e8a", "complementValid": True, "eventsAbsorbed": 2987000, "causalDepth": 10.9, "lastEvolution": "2025-07-14T11:52:00Z", "securityBound": 0.989},
    {"entityId": "ENT-LIDO", "generation": 1345, "sense": "e2d8c5f1", "antisense": "9a4b6e3d", "complementValid": True, "eventsAbsorbed": 5234000, "causalDepth": 13.1, "lastEvolution": "2025-07-14T11:59:00Z", "securityBound": 0.998},
    {"entityId": "ENT-CURVE", "generation": 1156, "sense": "c1a7f3b8", "antisense": "5d2e9c1f", "complementValid": True, "eventsAbsorbed": 4102000, "causalDepth": 12.0, "lastEvolution": "2025-07-14T11:55:00Z", "securityBound": 0.995},
    {"entityId": "ENT-TRIONBOT", "generation": 892, "sense": "f5b4d2a6", "antisense": "3e8c1f7a", "complementValid": True, "eventsAbsorbed": 1245000, "causalDepth": 9.7, "lastEvolution": "2025-07-14T11:57:00Z", "securityBound": 0.986},
    {"entityId": "ENT-JUPITER", "generation": 756, "sense": "8c3e7a1d", "antisense": "f2b9d4c6", "complementValid": True, "eventsAbsorbed": 2341000, "causalDepth": 10.2, "lastEvolution": "2025-07-14T11:50:00Z", "securityBound": 0.981},
    {"entityId": "ENT-PANCAKE", "generation": 1023, "sense": "7a2d5f8e", "antisense": "c4b1e3a9", "complementValid": False, "eventsAbsorbed": 3456000, "causalDepth": 11.4, "lastEvolution": "2025-07-14T11:48:00Z", "securityBound": 0.972},
    {"entityId": "ENT-OSMOSIS", "generation": 678, "sense": "d9f1c4b3", "antisense": "6e3a8d2f", "complementValid": True, "eventsAbsorbed": 1890000, "causalDepth": 9.1, "lastEvolution": "2025-07-14T11:45:00Z", "securityBound": 0.978},
    {"entityId": "ENT-RAYDIUM", "generation": 834, "sense": "b4e7a2c9", "antisense": "1f5d8e3b", "complementValid": True, "eventsAbsorbed": 2678000, "causalDepth": 10.6, "lastEvolution": "2025-07-14T11:53:00Z", "securityBound": 0.984},
    {"entityId": "ENT-SUIORACLE", "generation": 445, "sense": "a1c6d9f2", "antisense": "8b3e5a7c", "complementValid": True, "eventsAbsorbed": 890000, "causalDepth": 7.8, "lastEvolution": "2025-07-14T11:42:00Z", "securityBound": 0.965},
]

TIMESCALE_DB = {
    "status": "healthy",
    "totalEvents": 145892340,
    "eventsPerSecond": 2340.5,
    "storageUsed": "127.3 GB",
    "hypertableCount": 24,
    "compressionRatio": 12.7,
    "queryAvgLatency": 4.2,
    "retentionPeriod": "365 days",
    "oldestData": "2024-01-15T00:00:00Z",
    "newestData": "2025-07-14T12:00:00Z",
    "replicationStatus": "synced",
    "connectionPool": {"active": 18, "idle": 7, "max": 25},
}
